"""Add Table Food

Revision ID: 87b9b01c746a
Revises: eb7b83935e5a
Create Date: 2022-06-08 15:15:04.087322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "87b9b01c746a"
down_revision = "eb7b83935e5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "food",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("proteins", sa.Float(precision=2), nullable=False),
        sa.Column("lipids", sa.Float(precision=2), nullable=False),
        sa.Column("carbohydrates", sa.Float(precision=2), nullable=False),
        sa.Column("energy_value", sa.Float(precision=2), nullable=False),
        sa.Column("potassium", sa.Float(precision=2), nullable=False),
        sa.Column("phosphorus", sa.Float(precision=2), nullable=False),
        sa.Column("sodium", sa.Float(precision=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("food")
    # ### end Alembic commands ###
