"""Fix user entity

Revision ID: c8b043de3c2d
Revises: e020d9dbfdd8
Create Date: 2022-08-21 16:12:26.391408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8b043de3c2d"
down_revision = "e020d9dbfdd8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
