"""Unique user in personal data

Revision ID: e020d9dbfdd8
Revises: 3ca391ce2773
Create Date: 2022-07-06 10:48:01.380953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e020d9dbfdd8'
down_revision = '3ca391ce2773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'personal_data', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_data', type_='unique')
    # ### end Alembic commands ###
