"""add user profile photo

Revision ID: 46a49fc04572
Revises: 29bc568ed22e
Create Date: 2022-09-30 17:46:53.612968

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "46a49fc04572"
down_revision = "29bc568ed22e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("profile_photo", sqlalchemy_utils.types.url.URLType(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "profile_photo")
    # ### end Alembic commands ###
