"""Add Type of Meal

Revision ID: ffff59698355
Revises: 43c44cd284c4
Create Date: 2022-10-17 17:34:56.357642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ffff59698355"
down_revision = "43c44cd284c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "type_of_meal",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("calories_percentage", sa.Float(), nullable=True),
        sa.Column("lipids_percentage", sa.Float(), nullable=True),
        sa.Column("proteins_percentage", sa.Float(), nullable=True),
        sa.Column("carbohydrates_percentage", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("type_of_meal")
    # ### end Alembic commands ###
