"""Add Relation Food Category with Food

Revision ID: 36bff7b82540
Revises: f64efc327be5
Create Date: 2022-06-21 18:02:43.259565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36bff7b82540'
down_revision = 'f64efc327be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('food_category_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'food', 'food_category', ['food_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_column('food', 'food_category_id')
    # ### end Alembic commands ###
