"""add anthropometric data body photo

Revision ID: d2a0c4f159d0
Revises: 46a49fc04572
Create Date: 2022-10-06 18:31:54.744013

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d2a0c4f159d0"
down_revision = "46a49fc04572"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anthropometric_data",
        sa.Column("body_photo", sqlalchemy_utils.types.url.URLType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anthropometric_data", "body_photo")
    # ### end Alembic commands ###
