"""Add Biochemical Data

Revision ID: 3f4a081d3d91
Revises: a73206a8c93a
Create Date: 2022-10-10 18:16:00.325001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3f4a081d3d91"
down_revision = "a73206a8c93a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biochemical_data",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_proteins", sa.Float(precision=2), nullable=True),
        sa.Column("albumin", sa.Float(precision=2), nullable=True),
        sa.Column("urea", sa.Float(precision=2), nullable=True),
        sa.Column("uric_acid", sa.Float(precision=2), nullable=True),
        sa.Column("creatinine", sa.Float(precision=2), nullable=True),
        sa.Column("total_cholesterol", sa.Float(precision=2), nullable=True),
        sa.Column("hdl", sa.Float(precision=2), nullable=True),
        sa.Column("ldl", sa.Float(precision=2), nullable=True),
        sa.Column("glycemia", sa.Float(precision=2), nullable=True),
        sa.Column("hda1c", sa.Float(precision=2), nullable=True),
        sa.Column("fasting_glycemia", sa.Float(precision=2), nullable=True),
        sa.Column("post_prandial_glycemia", sa.Float(precision=2), nullable=True),
        sa.Column("total_bilirubin", sa.Float(precision=2), nullable=True),
        sa.Column("biliburin_direct", sa.Float(precision=2), nullable=True),
        sa.Column("alkaline_phosphatase", sa.Float(precision=2), nullable=True),
        sa.Column("ast_tgo", sa.Float(precision=2), nullable=True),
        sa.Column("alt_tgp", sa.Float(precision=2), nullable=True),
        sa.Column("ygt", sa.Float(precision=2), nullable=True),
        sa.Column("appointment_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointment.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("biochemical_data")
    # ### end Alembic commands ###
