"""Adding User last access

Revision ID: eb7b83935e5a
Revises: e23ab4e6d877
Create Date: 2022-06-02 16:39:32.774000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'eb7b83935e5a'
down_revision = 'e23ab4e6d877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_access', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_access')
    # ### end Alembic commands ###
