"""Fix biochemical relation with appointment

Revision ID: b970f76d3714
Revises: d6d076ed4385
Create Date: 2022-10-12 15:28:00.874972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b970f76d3714"
down_revision = "d6d076ed4385"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "biochemical_data", ["appointment_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "biochemical_data", type_="unique")
    # ### end Alembic commands ###
