"""Adding expiration column for the nutrition plan

Revision ID: 6171627b7af9
Revises: 917bfd438d05
Create Date: 2023-02-15 02:29:34.168324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6171627b7af9"
down_revision = "917bfd438d05"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nutritional_plan", sa.Column("validate_date", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nutritional_plan", "validate_date")
    # ### end Alembic commands ###
