"""Adding serving amounts in meals options

Revision ID: 83a474212a84
Revises: 6171627b7af9
Create Date: 2023-02-23 19:09:05.476037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "83a474212a84"
down_revision = "6171627b7af9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meals_options", sa.Column("amount", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meals_options", "amount")
    # ### end Alembic commands ###
